In [1]:
import torch

In [4]:
tensor = torch.tensor([[1, 2,6], [3, 4,7],[4, 5,8]])
tensor

tensor([[1, 2, 6],
        [3, 4, 7],
        [4, 5, 8]])

In [12]:
tensor.view([1,9])

tensor([[1, 2, 6, 3, 4, 7, 4, 5, 8]])

In [13]:
tensor.transpose(0, 1)

tensor([[1, 3, 4],
        [2, 4, 5],
        [6, 7, 8]])

In [14]:
tensor[:, [2, 1, 0]]

tensor([[6, 2, 1],
        [7, 4, 3],
        [8, 5, 4]])

In [15]:
tensor.permute(1, 0)

tensor([[1, 3, 4],
        [2, 4, 5],
        [6, 7, 8]])

In [21]:
tensor.transpose(-2, -1)

tensor([[1, 3, 4],
        [2, 4, 5],
        [6, 7, 8]])